/**
 * db/migrate-to-d1.mjs
 *
 * Reads all data/businesses/*.json files and writes SQL INSERT statements
 * to stdout that can be piped to wrangler d1 execute.
 *
 * Usage:
 *   node db/migrate-to-d1.mjs > db/seed-businesses.sql
 *   npx wrangler d1 execute getyoursitelive-db --file=db/seed-businesses.sql
 *
 * Or in one step:
 *   node db/migrate-to-d1.mjs | npx wrangler d1 execute getyoursitelive-db --command=-
 */

import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const bizDir = join(root, "data", "businesses");

function sqlEscape(str) {
  return str.replace(/'/g, "''");
}

const files = readdirSync(bizDir).filter((f) => f.endsWith(".json")).sort();

const lines = [];
lines.push("-- Generated by db/migrate-to-d1.mjs — do not edit manually");
lines.push("-- Run: npx wrangler d1 execute getyoursitelive-db --file=db/seed-businesses.sql");
lines.push("");

for (const file of files) {
  const raw = readFileSync(join(bizDir, file), "utf8");
  let biz;
  try {
    biz = JSON.parse(raw);
  } catch (err) {
    process.stderr.write(`SKIP ${file}: parse error — ${err.message}\n`);
    continue;
  }

  const slug = biz.slug ?? file.replace(".json", "");
  const name = biz.businessInfo?.name ?? slug;
  const category = biz.category ?? "Auto Repair";
  const theme = biz.theme ?? "modern";
  const content = sqlEscape(JSON.stringify(biz));
  const now = new Date().toISOString();

  lines.push(
    `INSERT INTO businesses (slug, name, category, theme, content, created_at, updated_at)` +
    ` VALUES ('${sqlEscape(slug)}', '${sqlEscape(name)}', '${sqlEscape(category)}', '${sqlEscape(theme)}', '${content}', '${now}', '${now}')` +
    ` ON CONFLICT(slug) DO UPDATE SET name = excluded.name, category = excluded.category, theme = excluded.theme, content = excluded.content, updated_at = excluded.updated_at;`,
  );
}

lines.push("");
process.stdout.write(lines.join("\n") + "\n");
process.stderr.write(`Generated INSERT statements for ${files.length} businesses.\n`);
